/** Default cell values for unmodelled APRS.CSV columns (fixture row). */

export const APRS_ROW_DEFAULTS: Record<string, string> = {
  'Manual TX Interval[s]': '0',
  'APRS Auto TX Interval[s]': '9',
  'Support For Roaming': '0',
  'Fixed Location Beacon': '0',
  'LatiDegree': '23',
  'LatiMinInt': '0',
  'LatiMinMark': '0',
  'North or South': '0',
  'LongtiDegree': '113',
  'LongtiMinInt': '0',
  'LongtiMinMark': '0',
  'East or West Hemisphere': '0',
  'channel1': '0',
  'slot1': '0',
  'Aprs Tg1': '234999',
  'Call Type1': '0',
  'channel2': '0',
  'slot2': '0',
  'Aprs Tg2': '0',
  'Call Type2': '0',
  'channel3': '0',
  'slot3': '0',
  'Aprs Tg3': '0',
  'Call Type3': '0',
  'channel4': '0',
  'slot4': '0',
  'Aprs Tg4': '0',
  'Call Type4': '0',
  'channel5': '0',
  'slot5': '0',
  'Aprs Tg5': '0',
  'Call Type5': '0',
  'channel6': '0',
  'slot6': '0',
  'Aprs Tg6': '0',
  'Call Type6': '0',
  'channel7': '0',
  'slot7': '0',
  'Aprs Tg7': '0',
  'Call Type7': '0',
  'channel8': '0',
  'slot8': '0',
  'Aprs Tg8': '0',
  'Call Type8': '0',
  'APRS TG': '1',
  'Call Type': '0',
  'Repeater Activation Delay[ms]': '0',
  'APRS TX Tone': '0',
  'TOCALL': 'APAT81',
  'TOCALL SSID': '0',
  'Your Call Sign': 'TEST01',
  'Your SSID': '0',
  'APRS Symbol Table': '/',
  'APRS Map Icon': '[',
  'Digipeater Path': 'WIDE1-1,WIDE2-1',
  'Enter Your Sending Text': '',
  'Transmission Frequency [MHz]': '145',
  'Transmit Delay[ms]': '0',
  'Send Sub Tone': '0',
  'CTCSS': '0',
  'DCS': '17',
  'Prewave Time[ms]': '0',
  'Transmit Power': '0',
  'Receive Filter1': '0',
  'Call Sign1': '',
  'SSID1': '16',
  'Receive Filter2': '0',
  'Call Sign2': '',
  'SSID2': '16',
  'Receive Filter3': '0',
  'Call Sign3': '',
  'SSID3': '16',
  'Receive Filter4': '0',
  'Call Sign4': '',
  'SSID4': '16',
  'Receive Filter5': '0',
  'Call Sign5': '',
  'SSID5': '16',
  'Receive Filter6': '0',
  'Call Sign6': '',
  'SSID6': '16',
  'Receive Filter7': '0',
  'Call Sign7': '',
  'SSID7': '16',
  'Receive Filter8': '0',
  'Call Sign8': '',
  'SSID8': '16',
  'Receive Filter9': '0',
  'Call Sign9': '',
  'SSID9': '16',
  'Receive Filter10': '0',
  'Call Sign10': '',
  'SSID10': '16',
  'Receive Filter11': '0',
  'Call Sign11': '',
  'SSID11': '16',
  'Receive Filter12': '0',
  'Call Sign12': '',
  'SSID12': '16',
  'Receive Filter13': '0',
  'Call Sign13': '',
  'SSID13': '16',
  'Receive Filter14': '0',
  'Call Sign14': '',
  'SSID14': '16',
  'Receive Filter15': '0',
  'Call Sign15': '',
  'SSID15': '16',
  'Receive Filter16': '0',
  'Call Sign16': '',
  'SSID16': '16',
  'Receive Filter17': '0',
  'Call Sign17': '',
  'SSID17': '16',
  'Receive Filter18': '0',
  'Call Sign18': '',
  'SSID18': '16',
  'Receive Filter19': '0',
  'Call Sign19': '',
  'SSID19': '16',
  'Receive Filter20': '0',
  'Call Sign20': '',
  'SSID20': '16',
  'Receive Filter21': '0',
  'Call Sign21': '',
  'SSID21': '16',
  'Receive Filter22': '0',
  'Call Sign22': '',
  'SSID22': '16',
  'Receive Filter23': '0',
  'Call Sign23': '',
  'SSID23': '16',
  'Receive Filter24': '0',
  'Call Sign24': '',
  'SSID24': '16',
  'Receive Filter25': '0',
  'Call Sign25': '',
  'SSID25': '16',
  'Receive Filter26': '0',
  'Call Sign26': '',
  'SSID26': '16',
  'Receive Filter27': '0',
  'Call Sign27': '',
  'SSID27': '16',
  'Receive Filter28': '0',
  'Call Sign28': '',
  'SSID28': '16',
  'Receive Filter29': '0',
  'Call Sign29': '',
  'SSID29': '16',
  'Receive Filter30': '0',
  'Call Sign30': '',
  'SSID30': '16',
  'Receive Filter31': '0',
  'Call Sign31': '',
  'SSID31': '16',
  'Receive Filter32': '0',
  'Call Sign32': '',
  'SSID32': '16',
  'POSITION': '0',
  'MIC-E': '0',
  'OBJECT': '0',
  'ITEM': '0',
  'MESSAGE': '0',
  'WX REPORT': '0',
  'NMEA REPORT': '0',
  'STATUS REPORT': '0',
  'OTHER': '0',
  'Transmission Frequency"0': '0',
  'Transmission Frequency"1': '0',
  'Transmission Frequency"2': '0',
  'Transmission Frequency"3': '0',
  'Transmission Frequency"4': '0',
  'Transmission Frequency"5': '0',
  'Transmission Frequency"6': '0',
  'Transmission Frequency"7': '0',
};
