/** Default cell values for unmodelled Channel.CSV columns (fixture row 2). */

export const CHANNEL_ROW_DEFAULTS: Record<string, string> = {
  'Busy Lock/TX Permit': 'Always',
  'Squelch Mode': 'Carrier',
  'Optional Signal': 'Off',
  'DTMF ID': '1',
  '2Tone ID': '1',
  '5Tone ID': '1',
  'PTT ID': 'Off',
  'PTT Prohibit': 'Off',
  Reverse: 'Off',
  'Digital Duplex': 'Off',
  'Slot Suit': 'Off',
  'AES Digital Encryption': 'Normal Encryption',
  'Digital Encryption': 'Off',
  'Call Confirmation': 'Off',
  'Talk Around(Simplex)': 'Off',
  'Work Alone': 'Off',
  'Custom CTCSS': '251.1',
  '2TONE Decode': '0',
  Ranging: 'Off',
  'Idle TX': 'Off',
  'APRS RX': 'Off',
  'Analog APRS PTT Mode': 'Off',
  'Digital APRS PTT Mode': 'Off',
  'APRS Report Type': 'Off',
  'Digital APRS Report Channel': '1',
  'Correct Frequency[Hz]': '0',
  'SMS Confirmation': 'Off',
  'Exclude channel from roaming': '0',
  'DMR MODE': '0',
  'DataACK Disable': '0',
  R5toneBot: '0',
  R5ToneEot: '0',
  'Auto Scan': '0',
  'Ana APRS Mute': '0',
  'Send Talker Alias DMR/NX': '0',
  AnaAprsTxPath: '0',
  ARC4: '0',
  ex_emg_kind: '0',
  Rpga_Mdc: '0',
  DisturEn: '0',
  DisturFreq: '0',
  dmr_crc_ignore: '0',
  compand: '0',
  tx_talkalaes: '0',
  dup_call: '0',
  tx_int: '0',
  BtRxState: '0',
  idle_tx: '0',
  nxdn_wn: '0',
  NxdnRpga: '0',
  nxdnSqCon: '0',
  NxdnTxBusy: '0',
  NxDnPttId: '0',
  EnRan: '0',
  DeRan: '0',
  NxdnEncry: '0',
  NxdnGroupId: '0',
  NxdnIdNum: '0',
  NxdnStateNum: '0',
  txcc: '1',
};
